name: CI

on:
  push:
    branches: ["**"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest
    - name: Run flake8
      run: flake8 .
    - name: Run tests
      run: |
        set -e
        pytest || if [ $? -eq 5 ]; then echo "No tests collected"; else exit $?; fi
